name: deploy to ecs
on:
    push:
        branches:
            main
    workflow_dispatch:

jobs:
   builddeploytoecs:
      runs-on: ubuntu-latest
      permissions :
        contents: read
        packages: write
      steps:
        - name: checkout clone from repo
          uses: actions/checkout@v3
        - name: set up java and maven
          uses: actions/setup-java@v3
          with:
             distribution: 'adopt'
             java-version: '11'

        - name: package with maven
          run: mvn package
          #make sure u update the url with the pub ip incase u stop and start your sonarqube server
        - name: code analysis with sonarqube 
          run:  mvn sonar:sonar -Dsonar.projectKey=xashywebapp -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.token=${{secrets.SONAR_LOGIN_TOKEN}}
        - name: upload artifact to github packages
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       
        - name: authenticate in aws env
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ${{secrets.AWS_REGION}}
